"""
H3x-Dash configuration.
Override via environment variables, a local .env file, or edit directly.

A .env file (generated by install.py) is loaded here before the settings are
read so its values populate the environment. Real environment variables always
win over .env, so a `MSF_PASS=... python3 h3x-dash.py` invocation still overrides
the file. Pure stdlib — no python-dotenv dependency.
"""
import os
from pathlib import Path


def _load_dotenv(path: Path) -> None:
    """Minimal .env loader: KEY=VALUE lines, '#' comments, optional quotes.

    Does NOT override variables already present in the environment.
    """
    try:
        if not path.is_file():
            return
        for raw in path.read_text().splitlines():
            line = raw.strip()
            if not line or line.startswith('#') or '=' not in line:
                continue
            key, _, val = line.partition('=')
            key = key.strip()
            if key.startswith('export '):
                key = key[len('export '):].strip()
            val = val.strip().strip('"').strip("'")
            if key and key not in os.environ:
                os.environ[key] = val
    except Exception:
        # A malformed .env must never stop the app from starting.
        pass


_load_dotenv(Path(__file__).parent / '.env')


class H3xConfig:

    # ── Version ───────────────────────────────────────────────────────────────
    # Single source of truth — surfaced in the sidebar under the logo. Bump on
    # each shipped build so operators can confirm which version is running.
    VERSION = '0.9.90.70'

    # ── Flask ─────────────────────────────────────────────────────────────────
    SECRET_KEY = os.environ.get('H3X_SECRET', 'h3x-dash-change-this-in-prod')

    # ── Metasploit RPC ────────────────────────────────────────────────────────
    MSF_HOST = os.environ.get('MSF_HOST', '127.0.0.1')
    MSF_PORT = int(os.environ.get('MSF_PORT', 55553))
    MSF_PASS = os.environ.get('MSF_PASS', 'msfrpc')
    MSF_SSL  = os.environ.get('MSF_SSL', 'false').lower() == 'true'

    # ── Paths ─────────────────────────────────────────────────────────────────
    BASE_DIR   = Path(__file__).parent
    LOOT_DIR   = BASE_DIR / 'loot'
    REPORT_DIR = BASE_DIR / 'reports'
    NMAP_DIR   = BASE_DIR / 'scans'
    LOG_DIR    = BASE_DIR / 'logs'

    # ── Adversary emulation (purple team) ─────────────────────────────────────
    # Invoke-AtomicRedTeam + MITRE CALDERA are wrapped as the *real* execution
    # backends — no synthetic telemetry. Point these at your lab install.
    ATOMICS_PATH     = os.environ.get('ATOMICS_PATH', str(Path.home() / 'AtomicRedTeam' / 'atomics'))
    PWSH_BIN         = os.environ.get('PWSH_BIN', 'pwsh')
    CALDERA_URL      = os.environ.get('CALDERA_URL', 'http://127.0.0.1:8888')
    CALDERA_API_KEY  = os.environ.get('CALDERA_API_KEY', '')
    # Correlation window: how long after a technique fires a Security Onion
    # detection may still land and still count as a catch (SIEM lag tolerance).
    RECONCILE_WINDOW_S = int(os.environ.get('RECONCILE_WINDOW_S', 900))

    # ── Scan defaults ─────────────────────────────────────────────────────────
    DEFAULT_TIMING  = 'T4'
    DEFAULT_PORTS   = 'driveby'
    DEFAULT_SCRIPTS = 'banner'

    @classmethod
    def init_dirs(cls):
        for d in [cls.LOOT_DIR, cls.REPORT_DIR, cls.NMAP_DIR, cls.LOG_DIR]:
            d.mkdir(parents=True, exist_ok=True)
        for sub in ('exploit', 'sessions', 'enumeration', 'scans'):
            (cls.LOG_DIR / sub).mkdir(parents=True, exist_ok=True)
